### ISSUE TITLE
Замечания к СРС 1 по курсу СУБД

### ISSUE THREAD

**Issue by ns-roxer** [go-park-mail-ru/2023_2_VIVE#13]
1. вопрос - почему все id сделаны типом uuid?
2. поля LOCATION и LEVEL названы в верхнем регистре, а все остальные в нижнем. Необходимо привести названия к нижнему регистру
3. `status TEXT NOT NULL DEFAULT 'serching'` - исправить опечатку в дефолтном значении
4. использования timestamp, заменить на timestamptz - учимся работать с часовыми поясами
5. у некоторых таблиц определен составной уникальный ключ, но явно не определен primary key. Не вижу в этом смысла. Замените в таких таблицах unique на primary key. Тем более, что в задании было четко сказано, что у всех таблиц PK должен быть задан явно!

**Comment by TheVovchenskiy** [comment]
> 1. вопрос - почему все id сделаны типом uuid?

Несколько причин:
- такой ключ безопаснее, так как он гарантирует отсутствие определенной последовательности значений,
- он гарантирует глобальную уникальность, то есть ключ, сгенерированный на одной машине не будет конфликтовать с другим ключом, сгенерированным на другой.
У него конечно есть и недостатки в виде большего объема занимаемой памяти, но нам и в прошлом семестре советовали его использовать и сейчас ментор подсказал про него.

upd. Изменил обратно на `serial` после объяснения на лекции.
